# Diese Felder bitte nicht ändern.
Rang: 1030
Wort: application
Wortart: nf

# Diese Felder gerne verbessern!
Wort mit Artikel: l’application
Femininum / Plural: ''
IPA: \a.pli.ka.sjɔ̃\
Definition: Anwendung
Register: '' # Beispiel: ↘Sachtext ↗Mündlich

# Beispielsätze müssen durch Zeilenumbrüche getrennt werden.
# Zwischen jedem Paar kommen zwei Zeilenumbrüche.
Beispielsätze: |-
  L’accord sera mis en application.
  Die Vereinbarung wird umgesetzt.

  Cette application est très utile.
  Diese Anwendung ist sehr nützlich.

  La police a pour mission l'application de la loi.
  Die Polizei hat die Aufgabe, das Gesetz anzuwenden.

  Il a beaucoup d'application à ses études.
  Er hat viel Eifer bei seinen Studien.

  L'application standard de ce logiciel est très simple.
  Die Standardanwendung dieser Software ist sehr einfach.

  La France est confrontée à des défis importants en matière d'application nationale du droit européen.
  Frankreich steht vor großen Herausforderungen bei der nationalen Umsetzung des Europarechts.

  L'application du droit étranger peut être complexe dans certains cas.
  Die Anwendung fremden Rechts kann in manchen Fällen komplex sein.

  L'application de mesures coercitives est une dernière option dans le cadre d'un conflit commercial.
  Die Verhängung von Zwangsmaßnahmen ist eine letzte Option im Rahmen eines Handelsstreits.

  La nouvelle loi entrera en application le 1er janvier prochain.
  Das neue Gesetz tritt am 1. Januar kommenden Jahres in Kraft.

  Le gouvernement a décidé de mettre en application un nouveau plan économique.
  Die Regierung hat beschlossen, einen neuen Wirtschaftsplan praktisch anzuwenden.

  La société a lancé une nouvelle application mobile pour faciliter les paiements.
  Das Unternehmen hat eine neue mobile App gestartet, um Zahlungen zu vereinfachen.

# Notizen können HTML enthalten. Um Beispielsätze zu formatieren, gerne dieses Format benutzen:
# <div class="examples">
#   <div class="fr">Un homme et une femme.</div>
#   <div class="de spoiler">Ein Mann und eine Frau.</div>
# </div>
Notiz: ''
