# Diese Felder bitte nicht ändern.
Rang: 4716
Wort: configuration
Wortart: nf

# Diese Felder gerne verbessern!
Wort mit Artikel: la configuration
Femininum / Plural: ''
IPA: \kɔ̃.fi.ɡy.ʁa.sjɔ̃\
Definition: Konfiguration, Anordnung
Register: ↗Sachtext

# Beispielsätze müssen durch Zeilenumbrüche getrennt werden.
# Zwischen jedem Paar kommen zwei Zeilenumbrüche.
Beispielsätze: |-
  La configuration institutionnelle rendrait une partition très difficile.
  Die institutionelle Konfiguration würde eine Partitionierung sehr schwierig machen.

  La configuration des meubles dans la pièce est importante.
  Die Anordnung der Möbel im Raum ist wichtig.

  La configuration du PC est un processus important pour assurer un bon fonctionnement.
  Die PC-Konfiguration ist ein wichtiger Prozess, um einen einwandfreien Betrieb zu gewährleisten.

  Il est possible de choisir entre une configuration automatique ou manuelle.
  Man kann zwischen einer automatischen oder manuellen Konfiguration wählen.

  La configuration matérielle est essentielle pour déterminer les performances du PC.
  Die Hardware-Konfiguration ist entscheidend für die Leistung des PCs.

  La configuration minimale est le minimum requis pour exécuter un programme ou un jeu.
  Die Minimalkonfiguration ist das Minimum, das erforderlich ist, um ein Programm oder ein Spiel auszuführen.

  La configuration requise est une liste de spécifications nécessaires pour un logiciel.
  Die Systemvoraussetzungen sind eine Liste der Spezifikationen, die für eine Software benötigt werden.

  Le fichier de configuration contient les paramètres et options du programme.
  Die Konfigurationsdatei enthält die Einstellungen und Optionen des Programms.

# Notizen können HTML enthalten. Um Beispielsätze zu formatieren, gerne dieses Format benutzen:
# <div class="examples">
#   <div class="fr">Un homme et une femme.</div>
#   <div class="de spoiler">Ein Mann und eine Frau.</div>
# </div>
Notiz: ''
